### ISSUE TITLE
integration fails since 2026.1.x

### ISSUE THREAD

**Issue by umrath** [lbbrhzn/ocpp#1843]
After updating to 2026.1.0 or 2026.1.1 the integration fails:

`Logger: homeassistant.setup
Quelle: setup.py:343
Erstmals aufgetreten: 14:47:45 (1 Vorkommnis)
Zuletzt protokolliert: 14:47:45

Setup failed for custom integration 'ocpp': Unable to import component: cannot import name 'Config' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1018, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ocpp/__init__.py", line 6, in <module>
    from homeassistant.core import Config, HomeAssistant
ImportError: cannot import name 'Config' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py). Did you mean: 'config'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1038, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1030, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ocpp/__init__.py", line 6, in <module>
    from homeassistant.core import Config, HomeAssistant
ImportError: cannot import name 'Config' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py). Did you mean: 'config'?`

**Comment by jthun** [comment]
What version of the integration are you using?

**Comment by pemillenaar** [comment]
Similar problem here. V0.10.9 and HA 2026.1.1.
Ocpp integration
Warning: Start transaction failed with response Rejected.

Can't get the charger to start anymore (WallBox Pulsar Plus). Used to work perfectly fine, but since HA 20261.1 not anymore.

**Comment by chopsywa** [comment]
Same here. v0.10.9. HA 2026.1.2 
I'm new and it worked once then stopped, so I have been tearing my hair out thinking it was me, or the EVSE (which works if I connect it back to EVCC). Glad I finally got this log entry when I turned the EVSE off and on again.
Logger: custom_components.ocpp
Source: custom_components/ocpp/ocppv16.py:611
integration: Open Charge Point Protocol (OCPP) ([documentation](https://github.com/lbbrhzn/ocpp/blob/main/README.md), [issues](https://github.com/lbbrhzn/ocpp/issues))
First occurred: 9:26:57 AM (1 occurrence)
Last logged: 9:26:57 AM

Failed with response: Rejected
My symptom is the same as @pemillenaar . The Charger won't start. The result in diagnostics for the connector is always. "EVSESuspended".

**Comment by stamanf** [comment]
I fixed mine by pasting the error to chatGPT.  Here's the summary of my changes:  

What’s going wrong

This line in your custom integration is the culprit:

from homeassistant.core import Config, HomeAssistant


In newer Home Assistant versions, Config no longer exists in homeassistant.core. It was removed quite a while ago, and older custom integrations still reference it.

That’s why HA is yelling:

cannot import name 'Config' from 'homeassistant.core'
Did you mean: 'config'?

(That hint is misleading — you don’t want config either.)

The fix (most likely)
**1. Edit this file**
/config/custom_components/ocpp/__init__.py

**2. Change the import**

❌ Old (broken):

from homeassistant.core import Config, HomeAssistant


✅ New (correct):

from homeassistant.core import HomeAssistant

3. Fix any function signatures using Config

Search for something like this:

async def async_setup(hass: HomeAssistant, config: Config) -> bool:


Change it to:

async def async_setup(hass: HomeAssistant, config: dict) -> bool:


or (even more modern, if supported):

async def async_setup(hass: HomeAssistant, config: dict) -> bool:
    ...


Config was just a typing helper — HA now uses plain dict.
