### ISSUE TITLE
AttributeError: 'DeviceRegistry' object has no attribute 'async_get_devices'. Did you mean: 'async_get_device'?

### ISSUE THREAD

**Issue by ColinTribal** [lbbrhzn/ocpp#2155]
**Describe the bug**

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/ocpp/chargepoint.py:990
Integration: Open Charge Point Protocol (OCPP) (documentation, issues)
First occurred: 09:34:17 (5 occurrences)
Last logged: 09:34:41

Error doing job: Task exception was never retrieved (task: None)
Traceback (most recent call last):
  File "/config/custom_components/ocpp/chargepoint.py", line 990, in update
    dr.async_get_devices(
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DeviceRegistry' object has no attribute 'async_get_devices'. Did you mean: 'async_get_device'?

**To Reproduce**
upgraded from 0.11.1 to 0.12.0
after restart of home assistant charger will not reconnect and this error is seen in the logs
Using latest home assistant with a Sync Energy Charger

**Expected behavior**
Allow the charger to connect

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Home Assistant Latest (docker image)
 - Browser N/A
 - Version 0.12.0

**Additional context**
Was connecting and working fine in 0.11.1
