### ISSUE TITLE
After upgrade to v11.4 - entities no longer refreshed

### ISSUE THREAD

**Issue by roku133** [lbbrhzn/ocpp#2132]
Configuration: 
Linux raspiIV 6.12.96+rpt-rpi-v7l
HA Container Core 2025.11.3
OCPP v11.4
Wallbox Vestel EVC04

With previous versions no issues at all with the OCPP integration, now upgraded to v11.4.

After starting a new charging session the entities have not longer been refreshed - the following error has been repeatedly shown in the protocol:

> Error doing job: Task exception was never retrieved (None)
> 
> Traceback (most recent call last):
>   File "/config/custom_components/ocpp/chargepoint.py", line 703, in update
>     dr.async_get_devices(
>     ^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'DeviceRegistry' object has no attribute 'async_get_devices'. Did you mean: 'async_get_device'?
> 

Nevertheless, the charging session was successfully started and finally stopped.

**Comment by drc38** [comment]
You'll need to upgrade HA, the recent registry call changes aren't backwards compatible.

**Comment by roku133** [comment]
Thank you very much for your quick clarification.
To be honest, I was afraid of that.
Unfortunately, I now have to migrate to a 64 bit OS since HA 2025.11.3 was the last version supporting 32 bit.
